### PR TITLE
Vanilla-ish Tatar Translation!

### PR DESCRIPTION
**Pull request by Amirhan-Taipovjan-Greatest-I**
Hello!
I need to know... where are "gui.volume", "gui.pitch" and "collector.all" strings appear and what's their context?

### CODE REVIEW

**Comment by CreativeMD** [comment]
Oh forgot to read your comment, sorry. The first two can appear anywhere. It's for volume or pitch configuration of sounds. The "collector.all" appears when selecting an item in the drop down list.

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> Oh forgot to read your comment, sorry. The first two can appear anywhere. It's for volume or pitch configuration of sounds.

Are "volume or pitch" translations can be capitalized? I need to know how these strings appear (via screenshot, if possible)


> The "collector.all" appears when selecting an item in the drop down list.

What actually word "Creative" means? In My language "Creative Mode" was translated similar to "Mode of creativity", so I need to know.

**Comment by CreativeMD** [comment]
Example for pitch and volume:

image

Example for the word Creative. It is used to describe the creative inventory:

image

**Comment by Amirhan-Taipovjan-Greatest-I** [comment]
> Example for pitch and volume:
> 
> image
> 
> Example for the word Creative. It is used to describe the creative inventory:
> 
> image

Ok, then there's no need in changing something in translations!

**Pull request merged**
